version: '3.1'
services:
  db:
    image: mysql
    environment:
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PWD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql-dev_data:/var/lib/mysql
    container_name: mysql
    ports:
      - '3306:3306'
    networks:
      - mysql
    command: --default-authentication-plugin=mysql_native_password
volumes:
  mysql-dev_data:
networks:
  mysql:
    name: mysql-network
    external: true
      
