version: '3.1'
services:
  docker-exercises:
    image: raccoondumpstermansion/development:exercise7v1.0.1
    environment:
      - DB_USER=${DB_USER}
      - DB_SERVER=${DB_SERVER}
      - DB_PWD=${DB_PWD}
      - DB_NAME=${DB_NAME}
    ports:
      - 8080:8080
    container_name: java
    depends_on:
      - db
    networks:
      - mysql

  db:
    image: mysql
    environment:
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PWD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql-dev_data:/var/lib/mysql
    container_name: mysql
    ports:
      - '3306:3306'
      - '33060:33060'
    networks:
      - mysql
    command: --default-authentication-plugin=mysql_native_password

  phpmyadmin:
    image: phpmyadmin
    environment:
      - PMA_HOST=mysql
    ports:
      - 8083:80
    container_name: phpmyadmin
    networks:
      - mysql

volumes:
  mysql-dev_data:
networks:
  mysql:
    name: mysql-network
    external: true
      
